### ISSUE TITLE
Diseño y maquetacion

### ISSUE THREAD

**Issue by UlisesGascon** [OSWeekends/memezinga#11]
### Pendiente
- Hablar con el equipo en SLACK
- Sincronizar con Vicky y Elena

**Comment by UlisesGascon** [comment]
Ana y Jesus

**Comment by ValKiriann** [comment]
yujuu

**Comment by txesus** [comment]
@ValKiriann te parece que los diseños los hagamos en sketch?

**Comment by ValKiriann** [comment]
Me parece perfecto !
