### ISSUE TITLE
favicon bug

### ISSUE THREAD

**Issue by UlisesGascon** [OSWeekends/memezinga#18]

**Comment by UlisesGascon** [comment]
Logo de Memezinga!

**Comment by txesus** [comment]
![favicon](https://user-images.githubusercontent.com/6781719/35524620-61026d82-0522-11e8-83ab-7866090ccca0.png)

**Comment by Optimus-73** [comment]
![favicon](https://user-images.githubusercontent.com/20280508/35540295-801ac254-0555-11e8-9ad2-c608c5d45e8f.png)
¿Que os parecería poner el logo redondeado?
Lo único es que habría que subirlo en png y pesaría un poquinin más ... Pero creo que queda más suave !
