### ISSUE TITLE
Landing con cuenta atrás

### ISSUE THREAD

**Issue by UlisesGascon** [OSWeekends/memezinga#2]
### Requisitos

- [x] Cuenta atras en js hasta la fecha... 19/01/2018
- [x] Hashtag de twitter con link para tuitear directo algo como "Que ansioso estoy para #xxxxxx sea real!! #LOL"
- [x] Nombre -> #6 
- [x] Descripción del proyecto
- [x] GH-PAGES para tener URL. [Guia](https://developer.mozilla.org/es/docs/Learn/Using_Github_pages) :-)

### Entrega el Lunes (David con Iñigo)

**Comment by k0sasp** [comment]
Asignar David e Iñigo!!

**Comment by UlisesGascon** [comment]
Conectado con bugs: #16 #17 #18
