### ISSUE TITLE
UX galería de memes

### ISSUE THREAD

**Issue by Optimus-73** [OSWeekends/memezinga#56]
![propuestamemezinga](https://user-images.githubusercontent.com/20280508/35280274-f6ef2e02-004f-11e8-8cc9-973301d10dd3.png)

**Comment by UlisesGascon** [comment]
Visto en slack. Gracias @Optimus-73. 

@txesus se hace cargo ;-)

**Comment by UlisesGascon** [comment]
hover sobre el texto... no funciona :trollface:

**Comment by Optimus-73** [comment]
Creo que quedaría mejor con un "transition" para el "hover"!
