### ISSUE TITLE
Definir un nombre molón

### ISSUE THREAD

**Issue by UlisesGascon** [OSWeekends/memezinga#6]
Poner ideas!

Deadline: Domingo a las 12pm

**Comment by UlisesGascon** [comment]
memeneame

**Comment by Sediug** [comment]
Pijus Memicus. https://www.youtube.com/watch?v=So4BuQ7HW3Y

**Comment by baumannzone** [comment]
memeoencima

**Comment by baumannzone** [comment]
memetelmeme

**Comment by Sediug** [comment]
memeoencima jajaja Literalmente +1 por esa

**Comment by ValKiriann** [comment]
memeneitor
creatimeme
construmeme
BAM! - Build a meme
memezinga
memenizame

**Comment by felixrigau** [comment]
Memeando

**Comment by Sediug** [comment]
Memento Cómo la peli

**Comment by Sediug** [comment]
NoMemesGuey

**Comment by UlisesGascon** [comment]
Memezingaaaaa!!!!  Ya veo las camisetas 😄 

Gracias @ValKiriann

**Comment by UlisesGascon** [comment]
Memezilla

**Comment by baumannzone** [comment]
sedicemem

**Comment by vmrodriguez95** [comment]
memelocomes

**Comment by felixrigau** [comment]
BAM! - Build a meme - (Me mola este de @ValKiriann)

**Comment by UlisesGascon** [comment]
Parece ser que se nos adelantaron... y algunos nombres ya estan en uso en Twitter como [#memeoencima](https://twitter.com/search?f=tweets&q=%23memeoencima&src=typd).

Lo que nos dificultará mucho la vida para calcular los retuits para birras gratis, pero [#memezinga](https://twitter.com/search?f=tweets&q=%23memezinga&src=typd)  es de los pocos que no tienen nada

Voto por pivotar el nombre :-D

**Comment by Vickysolo** [comment]
Vamos a poner el tweet, ayer decidimos que nos quedamos con #memezinga. Así que ya podéis empezar a twittear como si os fuera la vida en ello
