### ISSUE TITLE
Banco de imagenes para generar

### ISSUE THREAD

**Issue by UlisesGascon** [OSWeekends/memezinga#8]
### Pendiente
- [ ] ¿Que scrapeamos? Definir web, solo usamos JS de consola
- [ ] Generar un JSON con las URLs y categorizar
- [ ] Incluir el AJAX para el front. Relacionado con #5 
```json
[{
id: "id del meme usar UUID"
titulo: "titulo del meme",
url_meme: "url",
categorias: ["una", "dos.."]
}]
```

**Comment by k0sasp** [comment]
David e Iñigo
